spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e-com-db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:8086

server:
  port: 8082
