server:
  port: 8085

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8086
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri:  lb://USER-SERVICE
        predicates:
          - Path=/users/**

      - id: PRODUCT-SERVICE
        uri: lb://PRODUCT-SERVICE
        predicates:
          - Path=/products/**

      - id: COMMENT-SERVICE
        uri: lb://COMMENT-SERVICE
        predicates:
          - Path=/comments/**

      - id: CART-SERVICE
        uri: lb://CART-SERVICE
        predicates:
          - Path=/carts/**


