server:
  port: 8086

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AhmadFaraz961/config_server_e-com
          clone-on-start: true
          username: AhmadFaraz961
          password: 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
