spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e-com-db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: USER_SERVICE

server:
  port: 8081
